using System;
using System.Windows.Forms;

namespace C000UnitConverter
{
    /// <summary>
    /// Contains Initialization methods for Window class
    /// Big portion auto-generated by Windows Form Designer
    /// </summary>
    partial class C000Window
    {
        /// <summary>
        ///  Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        ///  Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        ///  Required method for Designer support - do not modify
        ///  the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.Windows.Forms.TabPage tabPageM;
            System.Windows.Forms.TableLayoutPanel tableLayoutPanelM;
            System.Windows.Forms.SplitContainer splitContainerM;
            System.Windows.Forms.Label labelGrams;
            System.Windows.Forms.Label labelPounds;
            System.Windows.Forms.Label labelOunces;
            System.Windows.Forms.TabPage tabPageL;
            System.Windows.Forms.TableLayoutPanel tableLayoutPanelL;
            System.Windows.Forms.SplitContainer splitContainerL;
            System.Windows.Forms.Label labelMetres;
            System.Windows.Forms.Label labelInches;
            System.Windows.Forms.Label labelFeet;
            System.Windows.Forms.Label labelYards;
            System.Windows.Forms.Label labelMiles;
            System.Windows.Forms.TabPage tabPageA;
            System.Windows.Forms.TableLayoutPanel tableLayoutPanelA;
            System.Windows.Forms.Label labelSqMiles;
            System.Windows.Forms.SplitContainer splitContainerA;
            System.Windows.Forms.Label labelMeters2;
            System.Windows.Forms.Label labelSqInches;
            System.Windows.Forms.Label labelSqFeet;
            System.Windows.Forms.Label labelSqYards;
            System.Windows.Forms.TabPage tabPageV;
            System.Windows.Forms.TableLayoutPanel tableLayoutPanelV;
            System.Windows.Forms.SplitContainer splitContainerV;
            System.Windows.Forms.Label labelMeters3;
            System.Windows.Forms.Label labelCuInches;
            System.Windows.Forms.Label labelGal;
            System.Windows.Forms.Label labelCuFeet;
            System.Windows.Forms.Label labelLitres;
            System.Windows.Forms.TabPage tabPageS;
            System.Windows.Forms.TableLayoutPanel tableLayoutPanelS;
            System.Windows.Forms.SplitContainer splitContainerS;
            System.Windows.Forms.Label labelMps;
            System.Windows.Forms.Label labelKmh;
            System.Windows.Forms.Label labelMph;
            System.Windows.Forms.Label labelFps;
            this.numericUpDownGrams = new System.Windows.Forms.NumericUpDown();
            this.comboBoxM = new System.Windows.Forms.ComboBox();
            this.numericUpDownLbs = new System.Windows.Forms.NumericUpDown();
            this.numericUpDownOz = new System.Windows.Forms.NumericUpDown();
            this.numericUpDownMi = new System.Windows.Forms.NumericUpDown();
            this.numericUpDownM = new System.Windows.Forms.NumericUpDown();
            this.comboBoxL = new System.Windows.Forms.ComboBox();
            this.numericUpDownIn = new System.Windows.Forms.NumericUpDown();
            this.numericUpDownF = new System.Windows.Forms.NumericUpDown();
            this.numericUpDownY = new System.Windows.Forms.NumericUpDown();
            this.numericUpDownMi2 = new System.Windows.Forms.NumericUpDown();
            this.numericUpDownM2 = new System.Windows.Forms.NumericUpDown();
            this.comboBoxA = new System.Windows.Forms.ComboBox();
            this.numericUpDownIn2 = new System.Windows.Forms.NumericUpDown();
            this.numericUpDownY2 = new System.Windows.Forms.NumericUpDown();
            this.numericUpDownF2 = new System.Windows.Forms.NumericUpDown();
            this.numericUpDownM3 = new System.Windows.Forms.NumericUpDown();
            this.comboBoxV = new System.Windows.Forms.ComboBox();
            this.numericUpDownIn3 = new System.Windows.Forms.NumericUpDown();
            this.numericUpDownGal = new System.Windows.Forms.NumericUpDown();
            this.numericUpDownF3 = new System.Windows.Forms.NumericUpDown();
            this.numericUpDownL = new System.Windows.Forms.NumericUpDown();
            this.numericUpDownFps = new System.Windows.Forms.NumericUpDown();
            this.numericUpDownMS = new System.Windows.Forms.NumericUpDown();
            this.comboBoxS = new System.Windows.Forms.ComboBox();
            this.numericUpDownKmh = new System.Windows.Forms.NumericUpDown();
            this.numericUpDownMph = new System.Windows.Forms.NumericUpDown();
            this.tabControl = new System.Windows.Forms.TabControl();
            tabPageM = new System.Windows.Forms.TabPage();
            tableLayoutPanelM = new System.Windows.Forms.TableLayoutPanel();
            splitContainerM = new System.Windows.Forms.SplitContainer();
            labelGrams = new System.Windows.Forms.Label();
            labelPounds = new System.Windows.Forms.Label();
            labelOunces = new System.Windows.Forms.Label();
            tabPageL = new System.Windows.Forms.TabPage();
            tableLayoutPanelL = new System.Windows.Forms.TableLayoutPanel();
            splitContainerL = new System.Windows.Forms.SplitContainer();
            labelMetres = new System.Windows.Forms.Label();
            labelInches = new System.Windows.Forms.Label();
            labelFeet = new System.Windows.Forms.Label();
            labelYards = new System.Windows.Forms.Label();
            labelMiles = new System.Windows.Forms.Label();
            tabPageA = new System.Windows.Forms.TabPage();
            tableLayoutPanelA = new System.Windows.Forms.TableLayoutPanel();
            labelSqMiles = new System.Windows.Forms.Label();
            splitContainerA = new System.Windows.Forms.SplitContainer();
            labelMeters2 = new System.Windows.Forms.Label();
            labelSqInches = new System.Windows.Forms.Label();
            labelSqFeet = new System.Windows.Forms.Label();
            labelSqYards = new System.Windows.Forms.Label();
            tabPageV = new System.Windows.Forms.TabPage();
            tableLayoutPanelV = new System.Windows.Forms.TableLayoutPanel();
            splitContainerV = new System.Windows.Forms.SplitContainer();
            labelMeters3 = new System.Windows.Forms.Label();
            labelCuInches = new System.Windows.Forms.Label();
            labelGal = new System.Windows.Forms.Label();
            labelCuFeet = new System.Windows.Forms.Label();
            labelLitres = new System.Windows.Forms.Label();
            tabPageS = new System.Windows.Forms.TabPage();
            tableLayoutPanelS = new System.Windows.Forms.TableLayoutPanel();
            splitContainerS = new System.Windows.Forms.SplitContainer();
            labelMps = new System.Windows.Forms.Label();
            labelKmh = new System.Windows.Forms.Label();
            labelMph = new System.Windows.Forms.Label();
            labelFps = new System.Windows.Forms.Label();
            tabPageM.SuspendLayout();
            tableLayoutPanelM.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDownGrams)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(splitContainerM)).BeginInit();
            splitContainerM.Panel1.SuspendLayout();
            splitContainerM.Panel2.SuspendLayout();
            splitContainerM.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDownLbs)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDownOz)).BeginInit();
            tabPageL.SuspendLayout();
            tableLayoutPanelL.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDownMi)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDownM)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(splitContainerL)).BeginInit();
            splitContainerL.Panel1.SuspendLayout();
            splitContainerL.Panel2.SuspendLayout();
            splitContainerL.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDownIn)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDownF)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDownY)).BeginInit();
            tabPageA.SuspendLayout();
            tableLayoutPanelA.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDownMi2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDownM2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(splitContainerA)).BeginInit();
            splitContainerA.Panel1.SuspendLayout();
            splitContainerA.Panel2.SuspendLayout();
            splitContainerA.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDownIn2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDownY2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDownF2)).BeginInit();
            tabPageV.SuspendLayout();
            tableLayoutPanelV.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDownM3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(splitContainerV)).BeginInit();
            splitContainerV.Panel1.SuspendLayout();
            splitContainerV.Panel2.SuspendLayout();
            splitContainerV.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDownIn3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDownGal)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDownF3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDownL)).BeginInit();
            tabPageS.SuspendLayout();
            tableLayoutPanelS.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDownFps)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDownMS)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(splitContainerS)).BeginInit();
            splitContainerS.Panel1.SuspendLayout();
            splitContainerS.Panel2.SuspendLayout();
            splitContainerS.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDownKmh)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDownMph)).BeginInit();
            this.tabControl.SuspendLayout();
            this.SuspendLayout();
            // 
            // tabPageM
            // 
            tabPageM.Controls.Add(tableLayoutPanelM);
            tabPageM.Location = new System.Drawing.Point(4, 24);
            tabPageM.Name = "tabPageM";
            tabPageM.Padding = new System.Windows.Forms.Padding(3);
            tabPageM.Size = new System.Drawing.Size(376, 334);
            tabPageM.TabIndex = 0;
            tabPageM.Text = "Mass";
            tabPageM.UseVisualStyleBackColor = true;
            // 
            // tableLayoutPanelM
            // 
            tableLayoutPanelM.ColumnCount = 2;
            tableLayoutPanelM.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            tableLayoutPanelM.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            tableLayoutPanelM.Controls.Add(this.numericUpDownGrams, 0, 0);
            tableLayoutPanelM.Controls.Add(splitContainerM, 1, 0);
            tableLayoutPanelM.Controls.Add(labelPounds, 1, 1);
            tableLayoutPanelM.Controls.Add(this.numericUpDownLbs, 0, 1);
            tableLayoutPanelM.Controls.Add(this.numericUpDownOz, 0, 2);
            tableLayoutPanelM.Controls.Add(labelOunces, 1, 2);
            tableLayoutPanelM.Location = new System.Drawing.Point(6, 6);
            tableLayoutPanelM.Name = "tableLayoutPanelM";
            tableLayoutPanelM.RowCount = 3;
            tableLayoutPanelM.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 33.33333F));
            tableLayoutPanelM.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 33.33333F));
            tableLayoutPanelM.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 33.33333F));
            tableLayoutPanelM.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            tableLayoutPanelM.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            tableLayoutPanelM.Size = new System.Drawing.Size(356, 336);
            tableLayoutPanelM.TabIndex = 2;
            // 
            // numericUpDownGrams
            // 
            this.numericUpDownGrams.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.numericUpDownGrams.DecimalPlaces = 3;
            this.numericUpDownGrams.Location = new System.Drawing.Point(14, 44);
            this.numericUpDownGrams.Maximum = new decimal(new int[] {
            1215752192,
            23,
            0,
            0});
            this.numericUpDownGrams.Name = "numericUpDownGrams";
            this.numericUpDownGrams.Size = new System.Drawing.Size(150, 23);
            this.numericUpDownGrams.TabIndex = 12;
            // 
            // splitContainerM
            // 
            splitContainerM.Anchor = System.Windows.Forms.AnchorStyles.None;
            splitContainerM.Cursor = System.Windows.Forms.Cursors.VSplit;
            splitContainerM.Location = new System.Drawing.Point(181, 3);
            splitContainerM.Name = "splitContainerM";
            // 
            // splitContainerM.Panel1
            // 
            splitContainerM.Panel1.Controls.Add(this.comboBoxM);
            splitContainerM.Panel1.Cursor = System.Windows.Forms.Cursors.Arrow;
            // 
            // splitContainerM.Panel2
            // 
            splitContainerM.Panel2.Controls.Add(labelGrams);
            splitContainerM.Panel2.Cursor = System.Windows.Forms.Cursors.Arrow;
            splitContainerM.Size = new System.Drawing.Size(172, 105);
            splitContainerM.SplitterDistance = 83;
            splitContainerM.SplitterWidth = 1;
            splitContainerM.TabIndex = 11;
            // 
            // comboBoxM
            // 
            this.comboBoxM.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.comboBoxM.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.comboBoxM.FormattingEnabled = true;
            this.comboBoxM.Items.AddRange(new object[] {
            "Giga",
            "Mega",
            "kilo",
            " ",
            "milli",
            "micro",
            "nano"});
            this.comboBoxM.Location = new System.Drawing.Point(27, 47);
            this.comboBoxM.Name = "comboBoxM";
            this.comboBoxM.Size = new System.Drawing.Size(55, 23);
            this.comboBoxM.TabIndex = 0;
            // 
            // labelGrams
            // 
            labelGrams.Anchor = System.Windows.Forms.AnchorStyles.Left;
            labelGrams.AutoSize = true;
            labelGrams.Location = new System.Drawing.Point(-3, 50);
            labelGrams.Name = "labelGrams";
            labelGrams.Size = new System.Drawing.Size(40, 15);
            labelGrams.TabIndex = 0;
            labelGrams.Text = "grams";
            // 
            // labelPounds
            // 
            labelPounds.Anchor = System.Windows.Forms.AnchorStyles.None;
            labelPounds.AutoSize = true;
            labelPounds.Location = new System.Drawing.Point(243, 160);
            labelPounds.Name = "labelPounds";
            labelPounds.Size = new System.Drawing.Size(47, 15);
            labelPounds.TabIndex = 3;
            labelPounds.Text = "Pounds";
            labelPounds.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // numericUpDownLbs
            // 
            this.numericUpDownLbs.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.numericUpDownLbs.DecimalPlaces = 3;
            this.numericUpDownLbs.Location = new System.Drawing.Point(14, 156);
            this.numericUpDownLbs.Maximum = new decimal(new int[] {
            1215752192,
            23,
            0,
            0});
            this.numericUpDownLbs.Name = "numericUpDownLbs";
            this.numericUpDownLbs.Size = new System.Drawing.Size(150, 23);
            this.numericUpDownLbs.TabIndex = 7;
            // 
            // numericUpDownOz
            // 
            this.numericUpDownOz.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.numericUpDownOz.DecimalPlaces = 3;
            this.numericUpDownOz.Location = new System.Drawing.Point(14, 268);
            this.numericUpDownOz.Maximum = new decimal(new int[] {
            1215752192,
            23,
            0,
            0});
            this.numericUpDownOz.Name = "numericUpDownOz";
            this.numericUpDownOz.Size = new System.Drawing.Size(150, 23);
            this.numericUpDownOz.TabIndex = 6;
            // 
            // labelOunces
            // 
            labelOunces.Anchor = System.Windows.Forms.AnchorStyles.None;
            labelOunces.AutoSize = true;
            labelOunces.Location = new System.Drawing.Point(243, 272);
            labelOunces.Name = "labelOunces";
            labelOunces.Size = new System.Drawing.Size(47, 15);
            labelOunces.TabIndex = 4;
            labelOunces.Text = "Ounces";
            labelOunces.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // tabPageL
            // 
            tabPageL.Controls.Add(tableLayoutPanelL);
            tabPageL.Location = new System.Drawing.Point(4, 24);
            tabPageL.Name = "tabPageL";
            tabPageL.Padding = new System.Windows.Forms.Padding(3);
            tabPageL.Size = new System.Drawing.Size(376, 334);
            tabPageL.TabIndex = 1;
            tabPageL.Text = "Length";
            tabPageL.UseVisualStyleBackColor = true;
            // 
            // tableLayoutPanelL
            // 
            tableLayoutPanelL.ColumnCount = 2;
            tableLayoutPanelL.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            tableLayoutPanelL.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            tableLayoutPanelL.Controls.Add(this.numericUpDownMi, 0, 4);
            tableLayoutPanelL.Controls.Add(this.numericUpDownM, 0, 0);
            tableLayoutPanelL.Controls.Add(splitContainerL, 1, 0);
            tableLayoutPanelL.Controls.Add(labelInches, 1, 1);
            tableLayoutPanelL.Controls.Add(this.numericUpDownIn, 0, 1);
            tableLayoutPanelL.Controls.Add(this.numericUpDownF, 0, 2);
            tableLayoutPanelL.Controls.Add(labelFeet, 1, 2);
            tableLayoutPanelL.Controls.Add(this.numericUpDownY, 0, 3);
            tableLayoutPanelL.Controls.Add(labelYards, 1, 3);
            tableLayoutPanelL.Controls.Add(labelMiles, 1, 4);
            tableLayoutPanelL.Location = new System.Drawing.Point(6, 6);
            tableLayoutPanelL.Name = "tableLayoutPanelL";
            tableLayoutPanelL.RowCount = 5;
            tableLayoutPanelL.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 20F));
            tableLayoutPanelL.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 20F));
            tableLayoutPanelL.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 20F));
            tableLayoutPanelL.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 20F));
            tableLayoutPanelL.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 20F));
            tableLayoutPanelL.Size = new System.Drawing.Size(356, 336);
            tableLayoutPanelL.TabIndex = 1;
            // 
            // numericUpDownMi
            // 
            this.numericUpDownMi.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.numericUpDownMi.DecimalPlaces = 3;
            this.numericUpDownMi.Location = new System.Drawing.Point(14, 290);
            this.numericUpDownMi.Maximum = new decimal(new int[] {
            1215752192,
            23,
            0,
            0});
            this.numericUpDownMi.Name = "numericUpDownMi";
            this.numericUpDownMi.Size = new System.Drawing.Size(150, 23);
            this.numericUpDownMi.TabIndex = 14;
            // 
            // numericUpDownM
            // 
            this.numericUpDownM.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.numericUpDownM.DecimalPlaces = 3;
            this.numericUpDownM.Location = new System.Drawing.Point(14, 22);
            this.numericUpDownM.Maximum = new decimal(new int[] {
            1215752192,
            23,
            0,
            0});
            this.numericUpDownM.Name = "numericUpDownM";
            this.numericUpDownM.Size = new System.Drawing.Size(150, 23);
            this.numericUpDownM.TabIndex = 12;
            // 
            // splitContainerL
            // 
            splitContainerL.Anchor = System.Windows.Forms.AnchorStyles.None;
            splitContainerL.Cursor = System.Windows.Forms.Cursors.VSplit;
            splitContainerL.Location = new System.Drawing.Point(181, 3);
            splitContainerL.Name = "splitContainerL";
            // 
            // splitContainerL.Panel1
            // 
            splitContainerL.Panel1.Controls.Add(this.comboBoxL);
            splitContainerL.Panel1.Cursor = System.Windows.Forms.Cursors.Arrow;
            // 
            // splitContainerL.Panel2
            // 
            splitContainerL.Panel2.Controls.Add(labelMetres);
            splitContainerL.Panel2.Cursor = System.Windows.Forms.Cursors.Arrow;
            splitContainerL.Size = new System.Drawing.Size(172, 61);
            splitContainerL.SplitterDistance = 83;
            splitContainerL.SplitterWidth = 1;
            splitContainerL.TabIndex = 11;
            // 
            // comboBoxL
            // 
            this.comboBoxL.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.comboBoxL.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.comboBoxL.FormattingEnabled = true;
            this.comboBoxL.Items.AddRange(new object[] {
            "Giga",
            "Mega",
            "kilo",
            " ",
            "milli",
            "micro",
            "nano"});
            this.comboBoxL.Location = new System.Drawing.Point(27, 25);
            this.comboBoxL.Name = "comboBoxL";
            this.comboBoxL.Size = new System.Drawing.Size(55, 23);
            this.comboBoxL.TabIndex = 0;
            // 
            // labelMetres
            // 
            labelMetres.Anchor = System.Windows.Forms.AnchorStyles.Left;
            labelMetres.AutoSize = true;
            labelMetres.Location = new System.Drawing.Point(-3, 28);
            labelMetres.Name = "labelMetres";
            labelMetres.Size = new System.Drawing.Size(43, 15);
            labelMetres.TabIndex = 0;
            labelMetres.Text = "metres";
            // 
            // labelInches
            // 
            labelInches.Anchor = System.Windows.Forms.AnchorStyles.None;
            labelInches.AutoSize = true;
            labelInches.Location = new System.Drawing.Point(246, 93);
            labelInches.Name = "labelInches";
            labelInches.Size = new System.Drawing.Size(41, 15);
            labelInches.TabIndex = 3;
            labelInches.Text = "Inches";
            labelInches.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // numericUpDownIn
            // 
            this.numericUpDownIn.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.numericUpDownIn.DecimalPlaces = 3;
            this.numericUpDownIn.Location = new System.Drawing.Point(14, 89);
            this.numericUpDownIn.Maximum = new decimal(new int[] {
            1215752192,
            23,
            0,
            0});
            this.numericUpDownIn.Name = "numericUpDownIn";
            this.numericUpDownIn.Size = new System.Drawing.Size(150, 23);
            this.numericUpDownIn.TabIndex = 7;
            // 
            // numericUpDownF
            // 
            this.numericUpDownF.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.numericUpDownF.DecimalPlaces = 3;
            this.numericUpDownF.Location = new System.Drawing.Point(14, 156);
            this.numericUpDownF.Maximum = new decimal(new int[] {
            1215752192,
            23,
            0,
            0});
            this.numericUpDownF.Name = "numericUpDownF";
            this.numericUpDownF.Size = new System.Drawing.Size(150, 23);
            this.numericUpDownF.TabIndex = 6;
            // 
            // labelFeet
            // 
            labelFeet.Anchor = System.Windows.Forms.AnchorStyles.None;
            labelFeet.AutoSize = true;
            labelFeet.Location = new System.Drawing.Point(252, 160);
            labelFeet.Name = "labelFeet";
            labelFeet.Size = new System.Drawing.Size(29, 15);
            labelFeet.TabIndex = 4;
            labelFeet.Text = "Feet";
            labelFeet.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // numericUpDownY
            // 
            this.numericUpDownY.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.numericUpDownY.DecimalPlaces = 3;
            this.numericUpDownY.Location = new System.Drawing.Point(14, 223);
            this.numericUpDownY.Maximum = new decimal(new int[] {
            1215752192,
            23,
            0,
            0});
            this.numericUpDownY.Name = "numericUpDownY";
            this.numericUpDownY.Size = new System.Drawing.Size(150, 23);
            this.numericUpDownY.TabIndex = 13;
            // 
            // labelYards
            // 
            labelYards.Anchor = System.Windows.Forms.AnchorStyles.None;
            labelYards.AutoSize = true;
            labelYards.Location = new System.Drawing.Point(249, 227);
            labelYards.Name = "labelYards";
            labelYards.Size = new System.Drawing.Size(35, 15);
            labelYards.TabIndex = 15;
            labelYards.Text = "Yards";
            labelYards.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // labelMiles
            // 
            labelMiles.Anchor = System.Windows.Forms.AnchorStyles.None;
            labelMiles.AutoSize = true;
            labelMiles.Location = new System.Drawing.Point(249, 294);
            labelMiles.Name = "labelMiles";
            labelMiles.Size = new System.Drawing.Size(35, 15);
            labelMiles.TabIndex = 16;
            labelMiles.Text = "Miles";
            labelMiles.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // tabPageA
            // 
            tabPageA.Controls.Add(tableLayoutPanelA);
            tabPageA.Location = new System.Drawing.Point(4, 24);
            tabPageA.Name = "tabPageA";
            tabPageA.Padding = new System.Windows.Forms.Padding(3);
            tabPageA.Size = new System.Drawing.Size(376, 334);
            tabPageA.TabIndex = 2;
            tabPageA.Text = "Area";
            tabPageA.UseVisualStyleBackColor = true;
            // 
            // tableLayoutPanelA
            // 
            tableLayoutPanelA.ColumnCount = 2;
            tableLayoutPanelA.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            tableLayoutPanelA.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            tableLayoutPanelA.Controls.Add(this.numericUpDownMi2, 0, 4);
            tableLayoutPanelA.Controls.Add(labelSqMiles, 0, 4);
            tableLayoutPanelA.Controls.Add(this.numericUpDownM2, 0, 0);
            tableLayoutPanelA.Controls.Add(splitContainerA, 1, 0);
            tableLayoutPanelA.Controls.Add(labelSqInches, 1, 1);
            tableLayoutPanelA.Controls.Add(this.numericUpDownIn2, 0, 1);
            tableLayoutPanelA.Controls.Add(labelSqFeet, 1, 2);
            tableLayoutPanelA.Controls.Add(labelSqYards, 1, 3);
            tableLayoutPanelA.Controls.Add(this.numericUpDownY2, 0, 3);
            tableLayoutPanelA.Controls.Add(this.numericUpDownF2, 0, 2);
            tableLayoutPanelA.Location = new System.Drawing.Point(6, 6);
            tableLayoutPanelA.Name = "tableLayoutPanelA";
            tableLayoutPanelA.RowCount = 5;
            tableLayoutPanelA.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 20F));
            tableLayoutPanelA.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 20F));
            tableLayoutPanelA.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 20F));
            tableLayoutPanelA.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 20F));
            tableLayoutPanelA.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 20F));
            tableLayoutPanelA.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            tableLayoutPanelA.Size = new System.Drawing.Size(356, 336);
            tableLayoutPanelA.TabIndex = 2;
            // 
            // numericUpDownMi2
            // 
            this.numericUpDownMi2.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.numericUpDownMi2.DecimalPlaces = 3;
            this.numericUpDownMi2.Location = new System.Drawing.Point(14, 290);
            this.numericUpDownMi2.Maximum = new decimal(new int[] {
            1215752192,
            23,
            0,
            0});
            this.numericUpDownMi2.Name = "numericUpDownMi2";
            this.numericUpDownMi2.Size = new System.Drawing.Size(150, 23);
            this.numericUpDownMi2.TabIndex = 16;
            // 
            // labelSqMiles
            // 
            labelSqMiles.Anchor = System.Windows.Forms.AnchorStyles.None;
            labelSqMiles.AutoSize = true;
            labelSqMiles.Location = new System.Drawing.Point(230, 294);
            labelSqMiles.Name = "labelSqMiles";
            labelSqMiles.Size = new System.Drawing.Size(74, 15);
            labelSqMiles.TabIndex = 13;
            labelSqMiles.Text = "Square miles";
            labelSqMiles.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // numericUpDownM2
            // 
            this.numericUpDownM2.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.numericUpDownM2.DecimalPlaces = 3;
            this.numericUpDownM2.Location = new System.Drawing.Point(14, 22);
            this.numericUpDownM2.Maximum = new decimal(new int[] {
            1215752192,
            23,
            0,
            0});
            this.numericUpDownM2.Name = "numericUpDownM2";
            this.numericUpDownM2.Size = new System.Drawing.Size(150, 23);
            this.numericUpDownM2.TabIndex = 12;
            // 
            // splitContainerA
            // 
            splitContainerA.Anchor = System.Windows.Forms.AnchorStyles.None;
            splitContainerA.Cursor = System.Windows.Forms.Cursors.VSplit;
            splitContainerA.Location = new System.Drawing.Point(181, 3);
            splitContainerA.Name = "splitContainerA";
            // 
            // splitContainerA.Panel1
            // 
            splitContainerA.Panel1.Controls.Add(this.comboBoxA);
            splitContainerA.Panel1.Cursor = System.Windows.Forms.Cursors.Arrow;
            // 
            // splitContainerA.Panel2
            // 
            splitContainerA.Panel2.Controls.Add(labelMeters2);
            splitContainerA.Panel2.Cursor = System.Windows.Forms.Cursors.Arrow;
            splitContainerA.Size = new System.Drawing.Size(172, 61);
            splitContainerA.SplitterDistance = 88;
            splitContainerA.SplitterWidth = 1;
            splitContainerA.TabIndex = 11;
            // 
            // comboBoxA
            // 
            this.comboBoxA.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.comboBoxA.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.comboBoxA.FormattingEnabled = true;
            this.comboBoxA.Items.AddRange(new object[] {
            "Giga",
            "Mega",
            "kilo",
            " ",
            "milli",
            "micro",
            "nano"});
            this.comboBoxA.Location = new System.Drawing.Point(30, 21);
            this.comboBoxA.Name = "comboBoxA";
            this.comboBoxA.Size = new System.Drawing.Size(55, 23);
            this.comboBoxA.TabIndex = 0;
            // 
            // labelMeters2
            // 
            labelMeters2.Anchor = System.Windows.Forms.AnchorStyles.Left;
            labelMeters2.AutoSize = true;
            labelMeters2.Location = new System.Drawing.Point(0, 25);
            labelMeters2.Name = "labelMeters2";
            labelMeters2.Size = new System.Drawing.Size(47, 15);
            labelMeters2.TabIndex = 0;
            labelMeters2.Text = "metres²";
            // 
            // labelSqInches
            // 
            labelSqInches.Anchor = System.Windows.Forms.AnchorStyles.None;
            labelSqInches.AutoSize = true;
            labelSqInches.Location = new System.Drawing.Point(227, 93);
            labelSqInches.Name = "labelSqInches";
            labelSqInches.Size = new System.Drawing.Size(80, 15);
            labelSqInches.TabIndex = 3;
            labelSqInches.Text = "Square inches";
            labelSqInches.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // numericUpDownIn2
            // 
            this.numericUpDownIn2.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.numericUpDownIn2.DecimalPlaces = 3;
            this.numericUpDownIn2.Location = new System.Drawing.Point(14, 89);
            this.numericUpDownIn2.Maximum = new decimal(new int[] {
            1215752192,
            23,
            0,
            0});
            this.numericUpDownIn2.Name = "numericUpDownIn2";
            this.numericUpDownIn2.Size = new System.Drawing.Size(150, 23);
            this.numericUpDownIn2.TabIndex = 7;
            // 
            // labelSqFeet
            // 
            labelSqFeet.Anchor = System.Windows.Forms.AnchorStyles.None;
            labelSqFeet.AutoSize = true;
            labelSqFeet.Location = new System.Drawing.Point(234, 160);
            labelSqFeet.Name = "labelSqFeet";
            labelSqFeet.Size = new System.Drawing.Size(66, 15);
            labelSqFeet.TabIndex = 4;
            labelSqFeet.Text = "Square feet";
            labelSqFeet.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // labelSqYards
            // 
            labelSqYards.Anchor = System.Windows.Forms.AnchorStyles.None;
            labelSqYards.AutoSize = true;
            labelSqYards.Location = new System.Drawing.Point(230, 227);
            labelSqYards.Name = "labelSqYards";
            labelSqYards.Size = new System.Drawing.Size(74, 15);
            labelSqYards.TabIndex = 14;
            labelSqYards.Text = "Square yards";
            labelSqYards.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // numericUpDownY2
            // 
            this.numericUpDownY2.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.numericUpDownY2.DecimalPlaces = 3;
            this.numericUpDownY2.Location = new System.Drawing.Point(14, 223);
            this.numericUpDownY2.Maximum = new decimal(new int[] {
            1215752192,
            23,
            0,
            0});
            this.numericUpDownY2.Name = "numericUpDownY2";
            this.numericUpDownY2.Size = new System.Drawing.Size(150, 23);
            this.numericUpDownY2.TabIndex = 6;
            // 
            // numericUpDownF2
            // 
            this.numericUpDownF2.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.numericUpDownF2.DecimalPlaces = 3;
            this.numericUpDownF2.Location = new System.Drawing.Point(14, 156);
            this.numericUpDownF2.Maximum = new decimal(new int[] {
            1215752192,
            23,
            0,
            0});
            this.numericUpDownF2.Name = "numericUpDownF2";
            this.numericUpDownF2.Size = new System.Drawing.Size(150, 23);
            this.numericUpDownF2.TabIndex = 17;
            // 
            // tabPageV
            // 
            tabPageV.Controls.Add(tableLayoutPanelV);
            tabPageV.Location = new System.Drawing.Point(4, 24);
            tabPageV.Name = "tabPageV";
            tabPageV.Size = new System.Drawing.Size(376, 334);
            tabPageV.TabIndex = 4;
            tabPageV.Text = "Volume";
            tabPageV.UseVisualStyleBackColor = true;
            // 
            // tableLayoutPanelV
            // 
            tableLayoutPanelV.ColumnCount = 2;
            tableLayoutPanelV.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            tableLayoutPanelV.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            tableLayoutPanelV.Controls.Add(this.numericUpDownM3, 0, 0);
            tableLayoutPanelV.Controls.Add(splitContainerV, 1, 0);
            tableLayoutPanelV.Controls.Add(labelCuInches, 1, 1);
            tableLayoutPanelV.Controls.Add(this.numericUpDownIn3, 0, 1);
            tableLayoutPanelV.Controls.Add(this.numericUpDownGal, 0, 2);
            tableLayoutPanelV.Controls.Add(labelGal, 1, 2);
            tableLayoutPanelV.Controls.Add(labelCuFeet, 1, 3);
            tableLayoutPanelV.Controls.Add(this.numericUpDownF3, 0, 3);
            tableLayoutPanelV.Controls.Add(this.numericUpDownL, 0, 4);
            tableLayoutPanelV.Controls.Add(labelLitres, 1, 4);
            tableLayoutPanelV.Location = new System.Drawing.Point(6, 6);
            tableLayoutPanelV.Name = "tableLayoutPanelV";
            tableLayoutPanelV.RowCount = 5;
            tableLayoutPanelV.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 20F));
            tableLayoutPanelV.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 20F));
            tableLayoutPanelV.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 20F));
            tableLayoutPanelV.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 20F));
            tableLayoutPanelV.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 20F));
            tableLayoutPanelV.Size = new System.Drawing.Size(356, 336);
            tableLayoutPanelV.TabIndex = 2;
            // 
            // numericUpDownM3
            // 
            this.numericUpDownM3.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.numericUpDownM3.DecimalPlaces = 3;
            this.numericUpDownM3.Location = new System.Drawing.Point(14, 22);
            this.numericUpDownM3.Maximum = new decimal(new int[] {
            1215752192,
            23,
            0,
            0});
            this.numericUpDownM3.Name = "numericUpDownM3";
            this.numericUpDownM3.Size = new System.Drawing.Size(150, 23);
            this.numericUpDownM3.TabIndex = 12;
            // 
            // splitContainerV
            // 
            splitContainerV.Anchor = System.Windows.Forms.AnchorStyles.None;
            splitContainerV.Cursor = System.Windows.Forms.Cursors.VSplit;
            splitContainerV.Location = new System.Drawing.Point(181, 3);
            splitContainerV.Name = "splitContainerV";
            // 
            // splitContainerV.Panel1
            // 
            splitContainerV.Panel1.Controls.Add(this.comboBoxV);
            splitContainerV.Panel1.Cursor = System.Windows.Forms.Cursors.Arrow;
            // 
            // splitContainerV.Panel2
            // 
            splitContainerV.Panel2.Controls.Add(labelMeters3);
            splitContainerV.Panel2.Cursor = System.Windows.Forms.Cursors.Arrow;
            splitContainerV.Size = new System.Drawing.Size(172, 61);
            splitContainerV.SplitterDistance = 83;
            splitContainerV.SplitterWidth = 1;
            splitContainerV.TabIndex = 11;
            // 
            // comboBoxV
            // 
            this.comboBoxV.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.comboBoxV.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.comboBoxV.FormattingEnabled = true;
            this.comboBoxV.Items.AddRange(new object[] {
            "Giga",
            "Mega",
            "kilo",
            " ",
            "milli",
            "micro",
            "nano"});
            this.comboBoxV.Location = new System.Drawing.Point(28, 19);
            this.comboBoxV.Name = "comboBoxV";
            this.comboBoxV.Size = new System.Drawing.Size(55, 23);
            this.comboBoxV.TabIndex = 0;
            // 
            // labelMeters3
            // 
            labelMeters3.Anchor = System.Windows.Forms.AnchorStyles.Left;
            labelMeters3.AutoSize = true;
            labelMeters3.Location = new System.Drawing.Point(-3, 23);
            labelMeters3.Name = "labelMeters3";
            labelMeters3.Size = new System.Drawing.Size(47, 15);
            labelMeters3.TabIndex = 0;
            labelMeters3.Text = "metres³";
            // 
            // labelCuInches
            // 
            labelCuInches.Anchor = System.Windows.Forms.AnchorStyles.None;
            labelCuInches.AutoSize = true;
            labelCuInches.Location = new System.Drawing.Point(229, 93);
            labelCuInches.Name = "labelCuInches";
            labelCuInches.Size = new System.Drawing.Size(75, 15);
            labelCuInches.TabIndex = 3;
            labelCuInches.Text = "Cubic inches";
            labelCuInches.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // numericUpDownIn3
            // 
            this.numericUpDownIn3.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.numericUpDownIn3.DecimalPlaces = 3;
            this.numericUpDownIn3.Location = new System.Drawing.Point(14, 89);
            this.numericUpDownIn3.Maximum = new decimal(new int[] {
            1215752192,
            23,
            0,
            0});
            this.numericUpDownIn3.Name = "numericUpDownIn3";
            this.numericUpDownIn3.Size = new System.Drawing.Size(150, 23);
            this.numericUpDownIn3.TabIndex = 7;
            // 
            // numericUpDownGal
            // 
            this.numericUpDownGal.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.numericUpDownGal.DecimalPlaces = 3;
            this.numericUpDownGal.Location = new System.Drawing.Point(14, 156);
            this.numericUpDownGal.Maximum = new decimal(new int[] {
            1215752192,
            23,
            0,
            0});
            this.numericUpDownGal.Name = "numericUpDownGal";
            this.numericUpDownGal.Size = new System.Drawing.Size(150, 23);
            this.numericUpDownGal.TabIndex = 6;
            // 
            // labelGal
            // 
            labelGal.Anchor = System.Windows.Forms.AnchorStyles.None;
            labelGal.AutoSize = true;
            labelGal.Location = new System.Drawing.Point(244, 160);
            labelGal.Name = "labelGal";
            labelGal.Size = new System.Drawing.Size(46, 15);
            labelGal.TabIndex = 4;
            labelGal.Text = "Gallons";
            labelGal.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // labelCuFeet
            // 
            labelCuFeet.Anchor = System.Windows.Forms.AnchorStyles.None;
            labelCuFeet.AutoSize = true;
            labelCuFeet.Location = new System.Drawing.Point(238, 227);
            labelCuFeet.Name = "labelCuFeet";
            labelCuFeet.Size = new System.Drawing.Size(58, 15);
            labelCuFeet.TabIndex = 16;
            labelCuFeet.Text = "Cube feet";
            labelCuFeet.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // numericUpDownF3
            // 
            this.numericUpDownF3.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.numericUpDownF3.DecimalPlaces = 3;
            this.numericUpDownF3.Location = new System.Drawing.Point(14, 223);
            this.numericUpDownF3.Maximum = new decimal(new int[] {
            1215752192,
            23,
            0,
            0});
            this.numericUpDownF3.Name = "numericUpDownF3";
            this.numericUpDownF3.Size = new System.Drawing.Size(150, 23);
            this.numericUpDownF3.TabIndex = 14;
            // 
            // numericUpDownL
            // 
            this.numericUpDownL.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.numericUpDownL.DecimalPlaces = 3;
            this.numericUpDownL.Location = new System.Drawing.Point(14, 290);
            this.numericUpDownL.Maximum = new decimal(new int[] {
            1215752192,
            23,
            0,
            0});
            this.numericUpDownL.Name = "numericUpDownL";
            this.numericUpDownL.Size = new System.Drawing.Size(150, 23);
            this.numericUpDownL.TabIndex = 13;
            // 
            // labelLitres
            // 
            labelLitres.Anchor = System.Windows.Forms.AnchorStyles.None;
            labelLitres.AutoSize = true;
            labelLitres.Location = new System.Drawing.Point(249, 294);
            labelLitres.Name = "labelLitres";
            labelLitres.Size = new System.Drawing.Size(35, 15);
            labelLitres.TabIndex = 15;
            labelLitres.Text = "Litres";
            labelLitres.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // tabPageS
            // 
            tabPageS.Controls.Add(tableLayoutPanelS);
            tabPageS.Location = new System.Drawing.Point(4, 24);
            tabPageS.Name = "tabPageS";
            tabPageS.Size = new System.Drawing.Size(376, 334);
            tabPageS.TabIndex = 3;
            tabPageS.Text = "Speed";
            tabPageS.UseVisualStyleBackColor = true;
            // 
            // tableLayoutPanelS
            // 
            tableLayoutPanelS.ColumnCount = 2;
            tableLayoutPanelS.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            tableLayoutPanelS.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            tableLayoutPanelS.Controls.Add(this.numericUpDownFps, 0, 3);
            tableLayoutPanelS.Controls.Add(this.numericUpDownMS, 0, 0);
            tableLayoutPanelS.Controls.Add(splitContainerS, 1, 0);
            tableLayoutPanelS.Controls.Add(labelKmh, 1, 1);
            tableLayoutPanelS.Controls.Add(this.numericUpDownKmh, 0, 1);
            tableLayoutPanelS.Controls.Add(this.numericUpDownMph, 0, 2);
            tableLayoutPanelS.Controls.Add(labelMph, 1, 2);
            tableLayoutPanelS.Controls.Add(labelFps, 1, 3);
            tableLayoutPanelS.Location = new System.Drawing.Point(6, 6);
            tableLayoutPanelS.Name = "tableLayoutPanelS";
            tableLayoutPanelS.RowCount = 4;
            tableLayoutPanelS.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 25F));
            tableLayoutPanelS.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 25F));
            tableLayoutPanelS.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 25F));
            tableLayoutPanelS.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 25F));
            tableLayoutPanelS.Size = new System.Drawing.Size(356, 336);
            tableLayoutPanelS.TabIndex = 2;
            // 
            // numericUpDownFps
            // 
            this.numericUpDownFps.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.numericUpDownFps.DecimalPlaces = 3;
            this.numericUpDownFps.Increment = new decimal(new int[] {
            0,
            0,
            0,
            0});
            this.numericUpDownFps.Location = new System.Drawing.Point(14, 282);
            this.numericUpDownFps.Maximum = new decimal(new int[] {
            1215752192,
            23,
            0,
            0});
            this.numericUpDownFps.Name = "numericUpDownFps";
            this.numericUpDownFps.Size = new System.Drawing.Size(150, 23);
            this.numericUpDownFps.TabIndex = 13;
            // 
            // numericUpDownMS
            // 
            this.numericUpDownMS.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.numericUpDownMS.DecimalPlaces = 3;
            this.numericUpDownMS.Location = new System.Drawing.Point(14, 30);
            this.numericUpDownMS.Maximum = new decimal(new int[] {
            1215752192,
            23,
            0,
            0});
            this.numericUpDownMS.Name = "numericUpDownMS";
            this.numericUpDownMS.Size = new System.Drawing.Size(150, 23);
            this.numericUpDownMS.TabIndex = 12;
            // 
            // splitContainerS
            // 
            splitContainerS.Anchor = System.Windows.Forms.AnchorStyles.None;
            splitContainerS.Cursor = System.Windows.Forms.Cursors.VSplit;
            splitContainerS.Location = new System.Drawing.Point(181, 3);
            splitContainerS.Name = "splitContainerS";
            // 
            // splitContainerS.Panel1
            // 
            splitContainerS.Panel1.Controls.Add(this.comboBoxS);
            splitContainerS.Panel1.Cursor = System.Windows.Forms.Cursors.Arrow;
            // 
            // splitContainerS.Panel2
            // 
            splitContainerS.Panel2.Controls.Add(labelMps);
            splitContainerS.Panel2.Cursor = System.Windows.Forms.Cursors.Arrow;
            splitContainerS.Size = new System.Drawing.Size(172, 78);
            splitContainerS.SplitterDistance = 83;
            splitContainerS.SplitterWidth = 1;
            splitContainerS.TabIndex = 11;
            // 
            // comboBoxS
            // 
            this.comboBoxS.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.comboBoxS.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.comboBoxS.FormattingEnabled = true;
            this.comboBoxS.Items.AddRange(new object[] {
            "Giga",
            "Mega",
            "kilo",
            " ",
            "milli",
            "micro",
            "nano"});
            this.comboBoxS.Location = new System.Drawing.Point(27, 34);
            this.comboBoxS.Name = "comboBoxS";
            this.comboBoxS.Size = new System.Drawing.Size(55, 23);
            this.comboBoxS.TabIndex = 0;
            // 
            // labelMps
            // 
            labelMps.Anchor = System.Windows.Forms.AnchorStyles.Left;
            labelMps.AutoSize = true;
            labelMps.Location = new System.Drawing.Point(-3, 37);
            labelMps.Name = "labelMps";
            labelMps.Size = new System.Drawing.Size(86, 15);
            labelMps.TabIndex = 0;
            labelMps.Text = "metres/second";
            // 
            // labelKmh
            // 
            labelKmh.Anchor = System.Windows.Forms.AnchorStyles.None;
            labelKmh.AutoSize = true;
            labelKmh.Location = new System.Drawing.Point(221, 118);
            labelKmh.Name = "labelKmh";
            labelKmh.Size = new System.Drawing.Size(92, 15);
            labelKmh.TabIndex = 3;
            labelKmh.Text = "kilometers/hour";
            labelKmh.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // numericUpDownKmh
            // 
            this.numericUpDownKmh.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.numericUpDownKmh.DecimalPlaces = 3;
            this.numericUpDownKmh.Location = new System.Drawing.Point(14, 114);
            this.numericUpDownKmh.Maximum = new decimal(new int[] {
            1215752192,
            23,
            0,
            0});
            this.numericUpDownKmh.Name = "numericUpDownKmh";
            this.numericUpDownKmh.Size = new System.Drawing.Size(150, 23);
            this.numericUpDownKmh.TabIndex = 7;
            // 
            // numericUpDownMph
            // 
            this.numericUpDownMph.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.numericUpDownMph.DecimalPlaces = 3;
            this.numericUpDownMph.Location = new System.Drawing.Point(14, 198);
            this.numericUpDownMph.Maximum = new decimal(new int[] {
            1215752192,
            23,
            0,
            0});
            this.numericUpDownMph.Name = "numericUpDownMph";
            this.numericUpDownMph.Size = new System.Drawing.Size(150, 23);
            this.numericUpDownMph.TabIndex = 6;
            // 
            // labelMph
            // 
            labelMph.Anchor = System.Windows.Forms.AnchorStyles.None;
            labelMph.AutoSize = true;
            labelMph.Location = new System.Drawing.Point(225, 202);
            labelMph.Name = "labelMph";
            labelMph.Size = new System.Drawing.Size(83, 15);
            labelMph.TabIndex = 4;
            labelMph.Text = "miles per hour";
            labelMph.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // labelFps
            // 
            labelFps.Anchor = System.Windows.Forms.AnchorStyles.None;
            labelFps.AutoSize = true;
            labelFps.Location = new System.Drawing.Point(223, 286);
            labelFps.Name = "labelFps";
            labelFps.Size = new System.Drawing.Size(88, 15);
            labelFps.TabIndex = 14;
            labelFps.Text = "feet per second";
            labelFps.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // tabControl
            // 
            this.tabControl.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.tabControl.Controls.Add(tabPageM);
            this.tabControl.Controls.Add(tabPageL);
            this.tabControl.Controls.Add(tabPageA);
            this.tabControl.Controls.Add(tabPageV);
            this.tabControl.Controls.Add(tabPageS);
            this.tabControl.Location = new System.Drawing.Point(0, -1);
            this.tabControl.Name = "tabControl";
            this.tabControl.SelectedIndex = 0;
            this.tabControl.Size = new System.Drawing.Size(384, 362);
            this.tabControl.TabIndex = 0;
            // 
            // C000Window
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(384, 361);
            this.Controls.Add(this.tabControl);
            this.MaximizeBox = false;
            this.MaximumSize = new System.Drawing.Size(400, 400);
            this.MinimumSize = new System.Drawing.Size(400, 400);
            this.Name = "C000Window";
            this.Text = "Unit Converter";
            tabPageM.ResumeLayout(false);
            tableLayoutPanelM.ResumeLayout(false);
            tableLayoutPanelM.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDownGrams)).EndInit();
            splitContainerM.Panel1.ResumeLayout(false);
            splitContainerM.Panel2.ResumeLayout(false);
            splitContainerM.Panel2.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(splitContainerM)).EndInit();
            splitContainerM.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDownLbs)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDownOz)).EndInit();
            tabPageL.ResumeLayout(false);
            tableLayoutPanelL.ResumeLayout(false);
            tableLayoutPanelL.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDownMi)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDownM)).EndInit();
            splitContainerL.Panel1.ResumeLayout(false);
            splitContainerL.Panel2.ResumeLayout(false);
            splitContainerL.Panel2.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(splitContainerL)).EndInit();
            splitContainerL.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDownIn)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDownF)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDownY)).EndInit();
            tabPageA.ResumeLayout(false);
            tableLayoutPanelA.ResumeLayout(false);
            tableLayoutPanelA.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDownMi2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDownM2)).EndInit();
            splitContainerA.Panel1.ResumeLayout(false);
            splitContainerA.Panel2.ResumeLayout(false);
            splitContainerA.Panel2.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(splitContainerA)).EndInit();
            splitContainerA.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDownIn2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDownY2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDownF2)).EndInit();
            tabPageV.ResumeLayout(false);
            tableLayoutPanelV.ResumeLayout(false);
            tableLayoutPanelV.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDownM3)).EndInit();
            splitContainerV.Panel1.ResumeLayout(false);
            splitContainerV.Panel2.ResumeLayout(false);
            splitContainerV.Panel2.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(splitContainerV)).EndInit();
            splitContainerV.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDownIn3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDownGal)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDownF3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDownL)).EndInit();
            tabPageS.ResumeLayout(false);
            tableLayoutPanelS.ResumeLayout(false);
            tableLayoutPanelS.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDownFps)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDownMS)).EndInit();
            splitContainerS.Panel1.ResumeLayout(false);
            splitContainerS.Panel2.ResumeLayout(false);
            splitContainerS.Panel2.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(splitContainerS)).EndInit();
            splitContainerS.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDownKmh)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDownMph)).EndInit();
            this.tabControl.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        /// <summary>
        /// Initializes event handlers for form controls
        /// </summary>
        private void InitEventHandlers()
        {
            comboBoxM.SelectedIndexChanged += new EventHandler(ComboBoxM_Changed);
            comboBoxL.SelectedIndexChanged += new EventHandler(ComboBoxL_Changed);
            comboBoxA.SelectedIndexChanged += new EventHandler(ComboBoxA_Changed);
            comboBoxV.SelectedIndexChanged += new EventHandler(ComboBoxV_Changed);
            comboBoxS.SelectedIndexChanged += new EventHandler(ComboBoxS_Changed);


            gChanged = new System.EventHandler(NumericUpDownGrams_ValueChanged);
            numericUpDownGrams.ValueChanged += gChanged;
            lbsChanged = new System.EventHandler(NumericUpDownLbs_ValueChanged);
            numericUpDownLbs.ValueChanged += lbsChanged;
            ozChanged = new System.EventHandler(NumericUpDownOz_ValueChanged);
            numericUpDownOz.ValueChanged += ozChanged;

            mChanged = new System.EventHandler(NumericUpDownM_ValueChanged);
            numericUpDownM.ValueChanged += mChanged;
            inChanged = new System.EventHandler(NumericUpDownIn_ValueChanged);
            numericUpDownIn.ValueChanged += inChanged;
            fChanged = new System.EventHandler(NumericUpDownF_ValueChanged);
            numericUpDownF.ValueChanged += fChanged;
            yChanged = new System.EventHandler(NumericUpDownY_ValueChanged);
            numericUpDownY.ValueChanged += yChanged;
            miChanged = new System.EventHandler(NumericUpDownMi_ValueChanged);
            numericUpDownMi.ValueChanged += miChanged;

            m2Changed = new System.EventHandler(NumericUpDownM2_ValueChanged);
            numericUpDownM2.ValueChanged += m2Changed;
            in2Changed = new System.EventHandler(NumericUpDownIn2_ValueChanged);
            numericUpDownIn2.ValueChanged += in2Changed;
            f2Changed = new System.EventHandler(NumericUpDownF2_ValueChanged);
            numericUpDownF2.ValueChanged += f2Changed;
            y2Changed = new System.EventHandler(NumericUpDownY2_ValueChanged);
            numericUpDownY2.ValueChanged += y2Changed;
            mi2Changed = new System.EventHandler(NumericUpDownMi2_ValueChanged);
            numericUpDownMi2.ValueChanged += mi2Changed;

            m3Changed = new System.EventHandler(NumericUpDownM3_ValueChanged);
            numericUpDownM3.ValueChanged += m3Changed;
            in3Changed = new System.EventHandler(NumericUpDownIn3_ValueChanged);
            numericUpDownIn3.ValueChanged += in3Changed;
            galChanged = new System.EventHandler(NumericUpDownGal_ValueChanged);
            numericUpDownGal.ValueChanged += galChanged;
            f3Changed = new System.EventHandler(NumericUpDownF3_ValueChanged);
            numericUpDownF3.ValueChanged += f3Changed;
            lChanged = new System.EventHandler(NumericUpDownL_ValueChanged);
            numericUpDownL.ValueChanged += lChanged;

            msChanged = new System.EventHandler(NumericUpDownMs_ValueChanged);
            numericUpDownMS.ValueChanged += msChanged;
            kmhChanged = new System.EventHandler(NumericUpDownKmh_ValueChanged);
            numericUpDownKmh.ValueChanged += kmhChanged;
            mphChanged = new System.EventHandler(NumericUpDownMph_ValueChanged);
            numericUpDownMph.ValueChanged += mphChanged;
            fpsChanged = new System.EventHandler(NumericUpDownFps_ValueChanged);
            numericUpDownFps.ValueChanged += fpsChanged;
        }

        /// <summary>
        /// Sets default values to controls
        /// </summary>
        private void InitDefaultValues()
        {
            comboBoxM.SelectedIndex = 2;
            comboBoxL.SelectedIndex = 3;
            comboBoxA.SelectedIndex = 3;
            comboBoxV.SelectedIndex = 3;
            comboBoxS.SelectedIndex = 3;
        }

        private TabControl tabControl;

        private EventHandler gChanged;
        private EventHandler ozChanged;
        private EventHandler lbsChanged;

        private EventHandler mChanged;
        private EventHandler inChanged;
        private EventHandler fChanged;
        private EventHandler yChanged;
        private EventHandler miChanged;
        
        private EventHandler m2Changed;
        private EventHandler in2Changed;
        private EventHandler f2Changed;
        private EventHandler y2Changed;
        private EventHandler mi2Changed;

        private EventHandler m3Changed;
        private EventHandler in3Changed;
        private EventHandler galChanged;
        private EventHandler f3Changed;
        private EventHandler lChanged;

        private EventHandler msChanged;
        private EventHandler kmhChanged;
        private EventHandler mphChanged;
        private EventHandler fpsChanged;

        private ComboBox comboBoxM;
        private ComboBox comboBoxL;
        private ComboBox comboBoxA;
        private ComboBox comboBoxV;
        private ComboBox comboBoxS;

        private NumericUpDown numericUpDownGrams;
        private NumericUpDown numericUpDownOz;
        private NumericUpDown numericUpDownLbs;
                              
        private NumericUpDown numericUpDownM;
        private NumericUpDown numericUpDownIn;
        private NumericUpDown numericUpDownF;
        private NumericUpDown numericUpDownY;
        private NumericUpDown numericUpDownMi;
                              
        private NumericUpDown numericUpDownM2;
        private NumericUpDown numericUpDownIn2;
        private NumericUpDown numericUpDownF2;
        private NumericUpDown numericUpDownY2;
        private NumericUpDown numericUpDownMi2;
                              
        private NumericUpDown numericUpDownM3;
        private NumericUpDown numericUpDownIn3;
        private NumericUpDown numericUpDownGal;
        private NumericUpDown numericUpDownF3;
        private NumericUpDown numericUpDownL;
                              
        private NumericUpDown numericUpDownMS;
        private NumericUpDown numericUpDownKmh;
        private NumericUpDown numericUpDownMph;
        private NumericUpDown numericUpDownFps;

    }
}